//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codziennik.RESX {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codziennik.RESX.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add entry.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insighter.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change questions below.
        /// </summary>
        public static string ChangeQuestions {
            get {
                return ResourceManager.GetString("ChangeQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What I&apos;m glad  for?
        ///Yesterday&apos;s triumph.
        /// </summary>
        public static string DefaultQuestions {
            get {
                return ResourceManager.GetString("DefaultQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! This operation is irreversible.
        /// </summary>
        public static string DeleteConfirmationDescription {
            get {
                return ResourceManager.GetString("DeleteConfirmationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really want to delete entry?.
        /// </summary>
        public static string DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file failed. Contact with the author of the app.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit entry: .
        /// </summary>
        public static string EditEntry {
            get {
                return ResourceManager.GetString("EditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of entries.
        /// </summary>
        public static string EntriesLack {
            get {
                return ResourceManager.GetString("EntriesLack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first entry by clicking +.
        /// </summary>
        public static string EntriesLackDescription {
            get {
                return ResourceManager.GetString("EntriesLackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries list:.
        /// </summary>
        public static string EntriesList {
            get {
                return ResourceManager.GetString("EntriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry deleted.
        /// </summary>
        public static string EntryDeleted {
            get {
                return ResourceManager.GetString("EntryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file failed. Contact with the author of the app.
        /// </summary>
        public static string ErrorMessageSaveFile {
            get {
                return ResourceManager.GetString("ErrorMessageSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, that you want to exit without saving changes?.
        /// </summary>
        public static string ExitQuestionDescription {
            get {
                return ResourceManager.GetString("ExitQuestionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitQuestionExit {
            get {
                return ResourceManager.GetString("ExitQuestionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay.
        /// </summary>
        public static string ExitQuestionStay {
            get {
                return ResourceManager.GetString("ExitQuestionStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit without saving?.
        /// </summary>
        public static string ExitQuestionTitle {
            get {
                return ResourceManager.GetString("ExitQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons made by Madebyoliver from www.flaticon.com on license Creative Commons BY 3.0.
        /// </summary>
        public static string IconsCredentials {
            get {
                return ResourceManager.GetString("IconsCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of questions.
        /// </summary>
        public static string QuestionLack {
            get {
                return ResourceManager.GetString("QuestionLack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default questions have been restored..
        /// </summary>
        public static string QuestionsLackDescription {
            get {
                return ResourceManager.GetString("QuestionsLackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read saved entries failed. Contact with the author of the app.
        /// </summary>
        public static string ReadEntriesFailed {
            get {
                return ResourceManager.GetString("ReadEntriesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read entry failed. Contact with the author of the app.
        /// </summary>
        public static string ReadEntryError {
            get {
                return ResourceManager.GetString("ReadEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read saved questions failed. Default questions have been restored. Contact with the author of the app.
        /// </summary>
        public static string ReadQuestionsError {
            get {
                return ResourceManager.GetString("ReadQuestionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default questions.
        /// </summary>
        public static string RestoreDefaultQuestions {
            get {
                return ResourceManager.GetString("RestoreDefaultQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save or delete changes before leave. Use buttons on the end of Q&amp;A list.
        /// </summary>
        public static string SaveOrDeleteDescription {
            get {
                return ResourceManager.GetString("SaveOrDeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save or delete changes.
        /// </summary>
        public static string SaveOrDeleteTitle {
            get {
                return ResourceManager.GetString("SaveOrDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save questions failed. Contact with the author of the app.
        /// </summary>
        public static string SaveQuestionsError {
            get {
                return ResourceManager.GetString("SaveQuestionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write about your day:.
        /// </summary>
        public static string TellAboutDay {
            get {
                return ResourceManager.GetString("TellAboutDay", resourceCulture);
            }
        }
    }
}
